apiVersion: skaffold/v1
kind: Config
build:
  tagPolicy:
    gitCommit: { }
  artifacts:
    - image: courier
      jib: { }
deploy:
  kustomize:
    path: "./.k8s/overlays/standard"
profiles:
  - name: observability
    deploy:
      kustomize:
        path: "./.k8s/overlays/observability"
