name: CI with Maven - Test and Build

# Trigger the workflow pull request,
# but only for the main branch
on:
  pull_request:
    branches: [ main ]
jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Test and Build with Maven
        run: ./mvnw --batch-mode clean verify
